#!/bin/bash
# Bootstrapping fresh xubuntu installation.
# All actions done by this script are idempotent.

ask() {
	if [ -z "$1" ]; then
		echo "Internal error: ask() called without question" >&2
		exit 1
	fi

	local question="$1"
	local answer

	echo -n "$question [y/N]: "
	read answer
	if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
		return 1
	fi

	return 0
}

# If called in non-interactive mode, always return true.
# Else return 0 or 1 based on answer.
interactive_ask() {
	if [ "$interactive" = false ]; then
		return 0
	fi

	ask "$1"
	return "$?"
}

install_packages() {
	echo "Installing packages"
	packages=$( cat packages.list | egrep -v "^#")
	sudo aptitude install -y $packages
}

main() {
	self_dir=$( dirname $( readlink -f ${BASH_SOURCE[0]} ) )

	dpkg -l 'aptitude' > /dev/null
	if [ $? -ne 0 ] ; then
		sudo apt-get install aptitude
	fi

	interactive=false

	for param in "$@"; do
		case "$param" in
			-i|--interactive)
				interactive=true
				echo "Interactive mode enabled."
			;;
		esac
	done

	interactive_ask "Install packages?" && install_packages

	echo "Executing scripts"
	for file in $( find $self_dir/scripts -type f )
	do
		. $file
	done

	echo "Bootstrapping is finished!"
}

main "$@"
exit 0
